### ISSUE TITLE
✨ Feat: 문해력 진단 - 요약 제출 & 요약 AI 피드백

### ISSUE THREAD

**Issue by adorableco** [KnowckknowcK/BE#24]
## **Issue**
- 지문에 대한 요약을 **수동으로** 제출하면 ChatGPT 기반 AI 피드백을 제공한다.
- 지문에 대한 요약을 **자동으로** 제출한 경우에는 피드백을 제공하지 않고 저장만 해둔다.
 - 자동 저장을 마지막으로 요약을 멈춘 경우, 같은 지문에 대한 요약을 재시도했을 때 이미 저장돼있는 요약을 제공해야 한다.

### ✨ 기능 리스트
- [ ] 요약 자동 제출
- [x] 요약 수동 제출
- [ ] 요약 AI 피드백

### TO-DO
- [ ]  `load-articles-controller` 에서 swagger 용 tag추가하기
---
